import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { build } from 'esbuild';
const worker = readFileSync('web/sw.js', 'utf8');
const shell = [...worker.match(/const SHELL = \[([\s\S]*?)\];/)[1].matchAll(/'([^']+)'/g)].map(m => m[1]);
const cached = new Set(shell);
for (const path of shell) {
  if (path === '/' || path === '/config.js') continue; // config is generated by prepare
  assert(existsSync(`web${path}`), `Missing required offline asset ${path}; run make vendor`);
}
const required = ['/vendor/v1/maplibre-gl-worker.mjs', '/vendor/v1/maplibre-gl-shared.mjs'];
const result = await build({ entryPoints: ['web/js/map.js', ...required.map(p => `web${p}`), 'web/vendor/v1/maplibre-gl.mjs', 'web/vendor/v1/opening-hours.mjs'],
  bundle: true, write: false, metafile: true, outdir: '/tmp/nicanav-graph', logLevel: 'silent' });
for (const input of Object.keys(result.metafile.inputs)) {
  assert(input.startsWith('web/'), `Unbundled package dependency ${input}`);
  assert(cached.has(`/${input.slice(4)}`), `Module missing from precache: ${input}`);
}
for (const name of ['nicanav', 'nicanav-night']) {
  const style = JSON.parse(readFileSync(`web/style/${name}.json`));
  assert(!style.glyphs, 'Offline style must not depend on uncached glyph ranges');
  for (const faces of Object.values(style['font-faces'])) for (const face of faces) assert(cached.has(face.url), `Font not precached: ${face.url}`);
  for (const suffix of ['.json', '.png', '@2x.json', '@2x.png']) assert(cached.has(style.sprite + suffix));
}
const html = readFileSync('web/index.html', 'utf8');
assert(!/<(?:script|link)[^>]+(?:src|href)="https?:/i.test(html), 'Runtime CDN dependency in shell');
console.log(`Offline dependency graph verified (${shell.length} precached paths).`);
