#!/usr/bin/env python3
"""Generate ``web/config.js`` from the environment at deploy time.

The PWA has no build step, so its runtime configuration cannot be baked in at
compile time and must not be hardcoded either — the same static files are served
from localhost during development and from a real hostname in production. This
writes the one small file the app reads before anything else.

    python3 scripts/render_web_config.py --output web/config.js
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from common.config import get_settings  # noqa: E402
from common.geo import CURATION_RADIUS_M, MGA_LAT, MGA_LON  # noqa: E402

TEMPLATE = """// Generated by scripts/render_web_config.py — do not edit by hand.
//
// The PWA reads this before anything else. It exists so the same static files
// serve from localhost and from the real hostname without a rebuild.
window.NICANAV_CONFIG = {config};
"""


def build_config() -> dict:
    settings = get_settings()
    return {
        "apiBase": "/api",
        "tilesBase": settings.tiles_base_url,
        "styleUrl": "/style/nicanav.json",
        "publicBaseUrl": settings.public_base_url,
        # Managua, not the airport: the map should open where people are.
        "center": [-86.2504, 12.1150],
        "zoom": 12,
        "mgaCenter": [MGA_LON, MGA_LAT],
        "curationRadiusM": CURATION_RADIUS_M,
        "defaultLanguage": settings.default_language,
        "offlineArchive": f"{settings.tiles_base_url}/circle.pmtiles",
        "attribution": "© OpenStreetMap contributors · Overture Maps Foundation",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "web" / "config.js")
    parser.add_argument("--print", action="store_true", help="write to stdout instead")
    args = parser.parse_args(argv)

    rendered = TEMPLATE.format(config=json.dumps(build_config(), indent=2, ensure_ascii=False))
    if args.print:
        sys.stdout.write(rendered)
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
